CREATE TYPE "user_role" AS ENUM (
	'user',
	'admin'
);

CREATE TYPE "membership_status" AS ENUM (
	'pending',
	'accepted'
);

CREATE TYPE "fundraising_status" AS ENUM (
	'active',
	'cancelled'
);

CREATE TYPE "transaction_type" AS ENUM (
	'deposit',
	'withdrawal',
	'payment',
	'refund'
);

CREATE TYPE "transaction_status" AS ENUM (
	'pending',
	'completed',
	'failed'
);

CREATE TYPE "report_type" AS ENUM (
	'users',
	'classes',
	'fundraisings',
	'transactions'
);

CREATE TABLE IF NOT EXISTS "users" (
    "id"                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email"             TEXT NOT NULL,
    "first_name"        TEXT NOT NULL,
    "last_name"         TEXT NOT NULL,
    "password_hash"     TEXT NOT NULL,
    "role"              USER_ROLE NOT NULL DEFAULT 'user',
    "is_blocked"        BOOLEAN NOT NULL DEFAULT false,
    "created_at"        TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at"        TIMESTAMP NOT NULL DEFAULT now(),
   
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "children" (
    "id"                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "parent_id"         INTEGER NOT NULL,
    "first_name"        TEXT NOT NULL,
    "last_name"         TEXT NOT NULL,
    "birth_date"        DATE NOT NULL,
    "avatar_file_id"    INTEGER,
    "created_at"        TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at"        TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "files" (
    "id"            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "filename"      TEXT NOT NULL,
    "content_type"  TEXT NOT NULL,
    "size_bytes"    INTEGER NOT NULL,
    "data"          BYTEA NOT NULL,
    "created_at"    TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "classes" (
    "id"            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "owner_id"      INTEGER NOT NULL,
    "name"          TEXT NOT NULL,
    "school"        TEXT NOT NULL,
    "city"          TEXT NOT NULL,
    "access_code"   VARCHAR(16) NOT NULL UNIQUE,
    "logo_file_id"  INTEGER,
    "is_blocked"    BOOLEAN NOT NULL DEFAULT false,
    "created_at"    TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at"    TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "class_memberships" (
    "id"            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "class_id"      INTEGER NOT NULL,
    "child_id"      INTEGER NOT NULL UNIQUE,
    "status"        MEMBERSHIP_STATUS NOT NULL DEFAULT 'pending',
    "requested_at"  TIMESTAMP NOT NULL DEFAULT now(),
    "decided_at"    TIMESTAMP,

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "fundraisings" (
    "id"                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "class_id"          INTEGER NOT NULL,
    "logo_file_id"      INTEGER,
    "name"              TEXT NOT NULL,
    "description"       TEXT NOT NULL,
    "start_at"          TIMESTAMP NOT NULL,
    "end_at"            TIMESTAMP NOT NULL,
    "amount_per_child"  NUMERIC(12,2) NOT NULL,
    "status"            FUNDRAISING_STATUS NOT NULL DEFAULT 'active',
    "cancelled_at"      TIMESTAMP,
    "is_blocked"        BOOLEAN NOT NULL DEFAULT false,
    "created_at"        TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at"        TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "fundraising_invoices" (
    "id"                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "fundraising_id"    INTEGER NOT NULL,
    "file_id"           INTEGER NOT NULL UNIQUE,
    "title"             TEXT,
    "created_at"        TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "wallets" (
    "id"                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"           INTEGER UNIQUE,
    "fundraising_id"    INTEGER UNIQUE,
    "iban"              VARCHAR(34) NOT NULL UNIQUE,
    "balance"           NUMERIC(12,2) NOT NULL DEFAULT 0,
    "created_at"        TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "transactions" (
    "id"                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "from_wallet_id"    INTEGER,
    "to_wallet_id"      INTEGER,
    "type"              TRANSACTION_TYPE NOT NULL,
    "amount"            NUMERIC(12,2) NOT NULL,
    "title"             TEXT NOT NULL,
    "status"            TRANSACTION_STATUS NOT NULL DEFAULT 'pending',
    "created_at"        TIMESTAMP NOT NULL DEFAULT now(),
    "completed_at"      TIMESTAMP,

    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "fundraising_contributions" (
    "id"                        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "fundraising_id"            INTEGER NOT NULL,
    "payer_id"                  INTEGER NOT NULL,
    "child_id"                  INTEGER NOT NULL,
    "transaction_id"            INTEGER NOT NULL UNIQUE,
    "refund_transaction_id"     INTEGER UNIQUE,
    "created_at"                TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);

-- TODO needs rework in the future
CREATE TABLE IF NOT EXISTS "reports" (
    "id"            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "report_type"   REPORT_TYPE NOT NULL,
    "parameters"    JSONB NOT NULL DEFAULT '{}',
    "file_id"       INTEGER,
    "generated_by"  INTEGER NOT NULL,
    "created_at"    TIMESTAMP NOT NULL DEFAULT now(),

    PRIMARY KEY("id")
);



ALTER TABLE "children"
    ADD FOREIGN KEY("parent_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "children"
    ADD FOREIGN KEY("avatar_file_id") REFERENCES "files"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "classes"
    ADD FOREIGN KEY("owner_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "class_memberships"
    ADD FOREIGN KEY("class_id") REFERENCES "classes"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "fundraisings"
    ADD FOREIGN KEY("class_id") REFERENCES "classes"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraisings"
    ADD FOREIGN KEY("logo_file_id") REFERENCES "files"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "fundraising_invoices"
    ADD FOREIGN KEY("fundraising_id") REFERENCES "fundraisings"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraising_invoices"
    ADD FOREIGN KEY("file_id") REFERENCES "files"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "wallets"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "transactions"
    ADD FOREIGN KEY("from_wallet_id") REFERENCES "wallets"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "transactions"
    ADD FOREIGN KEY("to_wallet_id") REFERENCES "wallets"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraising_contributions"
    ADD FOREIGN KEY("fundraising_id") REFERENCES "fundraisings"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraising_contributions"
    ADD FOREIGN KEY("payer_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraising_contributions"
    ADD FOREIGN KEY("child_id") REFERENCES "children"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "classes"
    ADD FOREIGN KEY("logo_file_id") REFERENCES "files"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "class_memberships"
    ADD FOREIGN KEY("child_id") REFERENCES "children"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "wallets"
    ADD FOREIGN KEY("fundraising_id") REFERENCES "fundraisings"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraising_contributions"
    ADD FOREIGN KEY("transaction_id") REFERENCES "transactions"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "fundraising_contributions"
    ADD FOREIGN KEY("refund_transaction_id") REFERENCES "transactions"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "reports"
    ADD FOREIGN KEY("file_id") REFERENCES "files"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "reports"
    ADD FOREIGN KEY("generated_by") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT;
